don't waste time making empty plots if compiling failed!

diff --git a/circle.yml b/circle.yml
--- a/circle.yml
+++ b/circle.yml
@@ -277,6 +277,12 @@ test:
         mv compare_to_reference $CIRCLE_ARTIFACTS/reference
       fi
 
+    #don't waste time making empty plots if compiling failed!
+    - |
+      if ! [ -f JHUGen ]; then
+        rm ~/reference_failed*
+      fi
+
     #============
     #syntax check
     #============
